### ISSUE TITLE
Statistical test for difference in medians

### ISSUE THREAD

**Issue by spentelow** [UBC-MDS/out_of_this_world#16]
Currently our README file refers to means and the EDA refers to (and plots) medians.  

Do the ANOVA and Turkey's HSD work for medians?

**Comment by spentelow** [comment]
After digging around a bit, I'm not sure that these tests work for medians.

It looks like there are a few good options for comparing TWO medians, but not many for comparing MULTIPLE medians.  The only test I've found that looks promising for this is Kruskal-Wallis.  The issue with Kruskal-Wallis is that it requires the assumption that the distributions all be identically shaped and scaled.  Not sure how strict this is though.  See the SO below for a discussion of this issue.

https://stats.stackexchange.com/questions/81864/hypothesis-test-for-difference-in-medians-among-more-than-two-samples

**Comment by AnitaLi-0371** [comment]
I can switch my plots to mean easily, but I just don’t know if it is okay
to use mean to represent data if they are skewed...

Maybe we could pick two shapes with the highest counts and compare them? Or
we could update the question to median for now and do some research at the
mean time? I think we need to be at least consistent for this week
assignment.

**Comment by chiragrank** [comment]
I found Kruskal-Wallis tests as a recommendation for comparing distribution where statistical assumption does not hold true at [statistical tests](https://www.scribbr.com/statistics/statistical-tests/#nonparametric). But here it says it is a non parametric test and does not make any assumption about the data. If that is true we can go ahead with it.

**Comment by spentelow** [comment]
From the wikipedia page:

> Since it is a non-parametric method, the Kruskal–Wallis test does not assume a normal distribution of the residuals, unlike the analogous one-way analysis of variance. If the researcher can make the assumptions of an identically shaped and scaled distribution for all groups, except for any difference in medians, then the null hypothesis is that the medians of all groups are equal, and the alternative hypothesis is that at least one population median of one group is different from the population median of at least one other group. 
- https://en.wikipedia.org/wiki/Kruskal%E2%80%93Wallis_one-way_analysis_of_variance

That being said, if we don't meet the condition of identically shaped and scaled distributions, I'm not sure what our null hypothesis becomes...?

**Comment by spentelow** [comment]
My suggestion for now is that we cite Kruskal-Wallis as the test we will perform and then dig into more deeply next week.  Does that work for everyone?

**Comment by JacobMcFarlane** [comment]
Good catch Steffen! I think we should switch to the Kruskal-Wallis Test and change our question to be in terms of distributions, although looking at Anita's graphs the distributions do seem to be pretty similar so the assumption of identically shaped and scaled distributions probably isn't absurd. Our new null hypothesis would just be that the durations of the different shapes all have the same underlying distribution, I think.

Are you making the changes or should I go ahead?

**Comment by spentelow** [comment]
Fine either way.  I was going to wait until the pull request was merged - not sure if things would get confused if I submitted a second one on the same file before that happens?

**Comment by JacobMcFarlane** [comment]
> Fine either way. I was going to wait until the pull request was merged - not sure if things would get confused if I submitted a second one on the same file before that happens?

Good point! Just approved that last request. @chiragrank and @AnitaLi-0371 are you guys alright with changing to a distribution framework and using the Kruskal-Wallace?

**Comment by chiragrank** [comment]
Yes, we can go ahead with the Kruskal-Wallace test and changing to a distribution framework

**Comment by AnitaLi-0371** [comment]
Thanks guys! Yes I am good with that as well.
