### ISSUE TITLE
Should we switch tests?

### ISSUE THREAD

**Issue by JacobMcFarlane** [UBC-MDS/out_of_this_world#19]
Hello everyone!

Apologies once again for missing the group meeting yesterday. 

Steffen and I talked with Analise (a 522 TA ) during lecture today and got some feedback on our choice of test. She suggested we log transform our data, and then go back to using an ANOVA / Tukey's Honest Significant Difference test for our principle analysis since our log transformed data actually looks fairly normal.

That seems like an appealing option to me, since a lot of the information on the Kruskal-Wallace H test seems to be a touch confusing, especially when you get in to measures of effect size. Let me know what you guys think!

**Comment by chiragrank** [comment]
I agree we should use kruskal-Wallace H test after we have eliminated the choice of using ANOVA. One of the concern of using ANOVA was making sure the normality assumption is true. Assuming normality assumption holds true, we use ANOVA. May be also consider some more analysis ([Normal Probability Plot](https://en.wikipedia.org/wiki/Normal_probability_plot)) to confirm it.

**Comment by spentelow** [comment]
The 'When to use it' section of [this webpage](http://www.biostathandbook.com/kruskalwallis.html) on Kuskal-Wallace has some interesting information on when ANOVA vs Kuskal-Wallace is more appropriate.  Based on that info and chatting with Analise, I would lean toward using an ANOVA test and being very explicit about our assumptions and reasoning.

**Comment by JacobMcFarlane** [comment]
So I wrote a little code in R to check some of the assumptions for an ANOVA on our log data (should be pushed to my fork if you want to take a look).

Essentially, the spot checks (e.g QQplots, looking at the actual variance values for each group) are borderline with the possible exception of "flash" which has a different variance and is clearly not normal (maybe we can just drop it and move on with our lives since it's not really a "shape" anyway?).

Levene's Test suggests that our groups have different variances and the Shapiro-Wilks test suggests that our data is not normally distributed. However, I think in this context these tests are overpowered. We have so many data points that they will detect differences that would have a trivial effect on our actual analysis. From [this Wikipedia article](https://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test) on the Shapiro-Wilks test:

>Like most statistical significance tests, if the sample size is sufficiently large this test may detect even trivial departures from the null hypothesis (i.e., although there may be some statistically significant effect, it may be too small to be of any practical significance); thus, additional investigation of the effect size is typically advisable, e.g., a Q–Q plot in this case.

Based on these results, I think we should drop flash and use an ANOVA approach. What are peoples thoughts here? Another option would be to ditch the groups approach, pick two groups, and just do a permutation test for difference in medians.

**Comment by JacobMcFarlane** [comment]
Per discussion on zoom, we decided on the Kruskal-Wallace
