### ISSUE TITLE
csv or feather?

### ISSUE THREAD

**Issue by spentelow** [UBC-MDS/out_of_this_world#21]
In today's lecture, Tiffany mentioned that it is generally good practice to save data that people may want to view directly in the csv format and use the feather format for intermediate files in cases where csvs are too slow.  

That being the case, I wonder whether we should switch to using csv files in our project since people may want to view the original and the cleaned data directly and we don't have any intermediate data files where the efficiency of feather would make a big difference.

What do others think?

**Comment by chiragrank** [comment]
I agree we would not have any **significant** performance issue with using csv. feather saves in a binary format which is efficient and one of the common way of saving different Data Structures I am exposed to. I may have a bit biased opinion in favor of feather so I am open to changes and look forward to hear from others.

**Comment by AnitaLi-0371** [comment]
I think either would work, and for this project I agree we do not have very large data so csv would work just fine. I think we can probably save them in both formats or just save them in cvs?

**Comment by chiragrank** [comment]
Giving more thought to it considering the point Steffen raised about viewability of the data from the lecture discussion, I feel then we can go ahead with the csv format.

**Comment by JacobMcFarlane** [comment]
We elected to use CSV files per our discussion on zoom.
