### ISSUE TITLE
Statistic choice

### ISSUE THREAD

**Issue by abaghela** [UBC-MDS/out_of_this_world#24]
It would be good if you state the exact hypothesis a KW test will prove/disprove. Can you use parametric statistics. Will you need to do any post hoc tests to identify which shape is significantly different from the rest?

**Comment by JacobMcFarlane** [comment]
Great suggestions, thanks! Updated to include exact hypothesis and a post-hoc test. We elected against a parametric approach because of significant violations of normality and heterogeneity of variance in even our log transformed data.
