### ISSUE TITLE
Remove unwanted shapes during pre-processing

### ISSUE THREAD

**Issue by spentelow** [UBC-MDS/out_of_this_world#46]
- remove extra shape categories:
    - Flash, Light, Unknown, Other, Changing

**Comment by spentelow** [comment]
Reopening this because I think it would be worth removing at least 'Cone' as well.  I looked at the counts for each and the ones on the low end are:

- Cone - 16
- Chevron - 34
- Diamond - 52
- Cigar - 56

All other shapes have at least 100 observations.  Again, with Cone being under 30, I think we should remove it.  Not sure about the other shapes noted above.

**Comment by JacobMcFarlane** [comment]
Could you elaborate a little more on where the analysis would be negatively effected by the smaller sample size? I for sure agree we should mention the smaller sample sizes if we present or discuss results related to any of those smaller shapes.

**Comment by spentelow** [comment]
That's a fair point.  I had thought we were removing all shapes which had very low observation counts (and Cone was just missed) but after looking at the cleaning code, I see that we are only removing the 'not-really-a-shape' shapes.  I think the original discussion about removing shapes with low observation counts may have come when we were looking at parametric tests but since we no longer use any parametric tests, there's no reason for it.

That said, I agree that we should include a note on the differences in number of observations among shapes in the report.  Perhaps we provide a summary table showing the number of observations for each shape?
