### ISSUE TITLE
Milestone 2 General Feedback & Report Feedback

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/out_of_this_world#59]
Hi Out of this world group!

Overall well done with your overall data analysis and rationale. 
The readme is very well done!
Your use of github issues and commit titles is good.

I have some specific comments about your Report:
1) missing Table of Contents
2) Figures need labels, and figures and tables should be referenced in the text, would also be nice to put in the report that the first figure is ordered by medians
3) Table 1 only has one value, can this be reported in the text?
4)Table 2 and the Duns Test figure are redundant, maybe only keep the figure in the report and leave the table in the eda document
5) would be nice to summarize the conclusion and say which shapes were most different looks like 'Changing, chevron, flash and unknown' are most different from the others. Maybe even a bar plot showing how many times each shape is different from the others would help show/compare witch are most different (just a thought)

**Comment by spentelow** [comment]
Since the Milestone 2 version of the report, a significant amount of text and a new plot have been added to the report which I address item number 4.  Items 1 to 3 have also been addressed (see linked pull request).
