### ISSUE TITLE
Duration data format

### ISSUE THREAD

**Issue by AnitaLi-0371** [UBC-MDS/out_of_this_world#6]
I look through the data `Duration` column, which is not clean and need some transformation. I could convert everything into `seconds` so they are comparable. However, there are quite a few values that I find hard to convert programmatically, examples include - `still here`, `seconds`, `unknown`, `some minutes`... Any suggestion what we should do with them? One simple way would just be removing all these, which may not be the best option.

Another issue with `Duration` is that, some entries are duration type, like 30-40minutes. Should I just take the average, ie 35 minutes?

**Comment by JacobMcFarlane** [comment]
I was looking through that as well- I didn't realize the data was that dirty, sorry! I'm thinking still here, seconds, unknown, some minutes and now are all just going to have to be tossed. I'm for taking the average of the time ranges given; we'll just have to be explicit in those decisions in our report. I'm happy to contribute to the cleaning since it's looking like this is going to be a fairly big job.

**Comment by AnitaLi-0371** [comment]
I will try some basic cleaning tonight and you all can review it tomorrow
to see if there are any additional cleaning you would like to do. I will
keep you posted.

Thanks everyone!

**Comment by JacobMcFarlane** [comment]
> I will try some basic cleaning tonight and you all can review it tomorrow to see if there are any additional cleaning you would like to do. I will keep you posted. Thanks everyone!

@AnitaLi-0371 I put together a quick pipe in the aliens.rmd file that gets enough of the cleaning done to at least start writing code for the other analysis if you want to use that as a base or just come back to the cleaning later. It's uploaded to my fork or just dm me on slack and I can send it to you there.

**Comment by chiragrank** [comment]
I looked into the data cleaning those observations as well and feel we can go ahead with the basic cleaning and get the pipeline ready. Can get back to it later down the line
