### ISSUE TITLE
Peer review feedback

### ISSUE THREAD

**Issue by Andrew-Tan** [UBC-MDS/out_of_this_world#62]
Hi all,

My name is Kaicheng Tan, and I'm one of the fellows that will review your assignments this week.

### Documentations
The documentations are great overall. Generally, README include all the required sections and the final report is properly formatted. Here's a few improvements you can consider making:

- The link to the final report seems broken. By looking at the raw code, it seems like you are using absolute HTTP link instead of relative links. Therefore, I would suggest using `doc/ufo_report.md` instead of `https://github.com/UBC-MDS/out_of_this_world/blob/main/doc/ufo_report.md`. GitHub will automatically substitute the relative link with the full link, like being described in this [post](https://github.blog/2013-01-31-relative-links-in-markup-files/).

- I noticed that you also included the html version of the final report. If your prefer the html version over markdown you can enable GitHub pages and point the final report to the GitHub pages.

### Code
The code is also great overall. There's a few minor issues in code style, but doesn't really impact the readability in general. Here's a few improvements you can consider making:

- There should be one space between the curly braces and the `function()` statement. So instead of:
  ```r
  function(){}
  ```
  should be:
  ```r
  function() {}
  ```

- Some tests reside in the same source file as the original code. That makes you have to run tests every time you run the script. Ideally, it would be better to separate them into the a `test` folder, like what was done in [dplyr](https://github.com/tidyverse/dplyr/tree/master/tests).

### Analysis
The analysis makes sense to me. It follows the hypotheses testing framework that we have learned in our statistic courses.

### Communication
Great in general. Hypotheses are clearly stated in the report, as well as the conclusion. Particularly, I like the visualizations which are very intuitive and beautiful to look at. 

For the conclusion:
> The Kruskal Wallis H Test resulted in a p-value much less than our stated significance level of 0.05,  therefore, we reject the null hypothesis that the mean ranks of the duration of sightings are equal for all shapes.

Since this is the core conclusion in your report, I would suggest finding some way(s) to highlight it to make it more visible. For example, you can add a (sub-)section title for this paragraph, or/and make the text bold, etc.

**Comment by spentelow** [comment]
Thanks very much for your feedback and suggestions Andrew.  We have addressed the issues that you identified.
