### ISSUE TITLE
Peer review feedback from Alex Truong

### ISSUE THREAD

**Issue by athy9193** [UBC-MDS/out_of_this_world#63]
Hi all,

I am Alex Truong, kindly find below my peer review feedback on your group project.

### Documentation:
• Your report and code scripts are well-documented and very clear to follow.
• The Dependencies Diagram also helps readers to better understand the structure of your project's Github repository. 👍 

### Code: 
• When I run `make all`, I incurred the following error. Is there some other package I need to installed besides the ones mentioned in Dependencies section?
• I think your code somewhat works but I think toward the end, right before generating the report, it broke. 
![image](https://user-images.githubusercontent.com/56498756/101586894-d8299b00-3a1d-11eb-8ca5-8b6c0ba04b1b.png)

• The following syntax are highlighted in times_cleaning.R at row 15 in analysis.R at row 14 when I opened it in Rstudios. Maybe you can check it out 
![image](https://user-images.githubusercontent.com/56498756/101586971-0e671a80-3a1e-11eb-86cd-e4ed3a82c16b.png)

### Analysis and reasoning: 

• In the Introduction section: you mentioned many causes associated with different UFO reported shapes, and many causes related to the different duration of sighting. I think it would be clearer to communicate the eventual research question linking the reported shaped and duration of sighting, which would tie nicely with your hypotheses in subsequent sections.

• In the Data Processing section: I think the omitting the non-shape records may skew the result toward clearly specified shape. I think we shared this view as you did acknowledge this in your report.

### Communication: 
• Save for some minor typos, I think the report is great in communicate clearly to audience on the major topic, the analysis method as well as the final conclusion.
• I also think the report has great visualizations, they really help readers follow the analysis and very pleasing to look at 👍 

### Overall Feedback:
* I think this is a good project barring some technical coding issues. You communicate your topic and analysis in a clear, succinct and effective way. Below are some suggestions that I think could further refine your project.

### Suggestions: 
• **Documentation**:
	- The link to the report mentioned in README.md needs to be updated since it leads to a obsolete link for an .md file at the moment
	- In terms of installation of packages, as there are many packages to install and some of them may not be needed for potential audience on a frequent basis, I think maybe you could explore streamlining it in an environment file for end-users to install virtual environment. This would make the environment setting up process more organized and convenient for end users. Containerization with Docker is a great option too.
	- There are some packages that have not been incorporated in the report references. I saw more references in your .bib files but somehow they are not reflected in the final PDF. Maybe you can check on that.

• **Analysis and reasoning**:
	- For data processing: grouping these categories in a non-defined shape group rather than omitting them would be another viable option you could explore.
       -  I think Dunn Test is great in comparing among the different shapes. What would be a great addition to this is maybe a regression analysis to study the relationship between the reported shaped and duration of sighting,

**Comment by spentelow** [comment]
Thanks very much for reviewing our project and for the helpful feedback.  We have taken your suggestions into consideration as we have updated our report and analysis and corrected the errors that you noted (broken links etc.).
