### ISSUE TITLE
Peer review from Santiago Rugeles Schoonewolff

### ISSUE THREAD

**Issue by ansarusc** [UBC-MDS/out_of_this_world#67]
Hi classmates,  my name is Santiago and I´ll be providing some feedback on your project. First of all, I wanted to mention your excellent project organization. The data is included, both in its raw and processed formats, the scripts, folders, and reports have clear names and most importantly, the commits´ names are clear and understandable.

### Code

There is a 'pandoc' dependency error when I try to run the make file, although I imagine this will be corrected once the docker file is implemented. 

### Analysis

The data preprocessing was very well done, I support every single decision you made, as it must have been hard to clean both the shapes and the sight duration. The conclusions and findings are well presented. I understood the usage of the Dunn test once you were 95% certain that at least one shape had a different sight duration than the rest, yet the selection of the Kruskal-Wallis H is not completely clear for me.

### Documentation

Overall, the scripts have good documentation explaining what is expected of each of them.  Moreover, the reports are well written, with proper grammar. There are a few minor typos, but nothing that affects the general readability.  The makefile png is a great addition to understand the overall workflow of the project.

### Suggestions

* The link to the final report is broken. If you want to include the report as an HTML instead of a markdown document, this link for rendering HTML in GitHub might be useful ( we used it back in DSCI 521):
          https://htmlpreview.github.io/?
* I understand that the objective of this project is to study the sight durations of different UFO shapes, nonetheless, it would be more engaging to state the inferential question clearly at the beginning of the Readme.
* I suggest to include a better explanation on why the Kruskal-Wallis H test was selected and how does it help with the skewed distributions and variance sizes (this is, of course, not a must, just for those that are not that well-versed in this test).

**Comment by spentelow** [comment]
Thanks very much for the encouraging words and helpful review comments Santiago.  We have taking your suggestions into consideration as we have updated our project and addressed the issues you identified.
